### ISSUE TITLE
Not working on Sierra 10.12.4 in Spanish (with night mode)

### ISSUE THREAD

**Issue by gonzab** [paulrudy/alfred-toggle-do-not-disturb#1]
The title talks by itself. I will try later a fix, but FYI.

**Comment by paulrudy** [comment]
Try going into the workflow, and editing both of the Applescripts. Change "Notification" to "Notificacion"

**Comment by gonzab** [comment]
Thanks!!! It works!

**Comment by paulrudy** [comment]
Great! Glad I could help
