### ISSUE TITLE
Doesn't work for macOS Sierra

### ISSUE THREAD

**Issue by raphaklr** [paulrudy/alfred-toggle-do-not-disturb#2]
Could you maybe update the script to work with macOS Sierra / macOS High Sierra?

**Comment by paulrudy** [comment]
It works for me on High Sierra and worked before on Sierra. You might want to make sure Alfred 3 is checked under System Preferences > Security & Privacy > Privacy tab > Accessibility

**Comment by raphaklr** [comment]
Doesn't work for me, although the option in system preferences is checked ¯\_(ツ)_/¯ Thanks anyway!

**Comment by paulrudy** [comment]
Are you using a language other than English as your system language? If so, you'll need to edit the workflow: the /usr/bin/osascript part has this line:

`tell (every menu bar whose title of menu bar item 1 contains "Notification")
				click (1st menu bar item whose title contains "Notification")
`

"Notification" should be changed to the appropriate word in the system UI elements in your language.

**Comment by raphaklr** [comment]
Thank you, it's finally working! I also edited the workflow in my first try, but I apparently used the wrong localization string. One final question: Why do you have those delays in there? For example, if I turn it on, it takes 3 seconds before it does the "click".

**Comment by paulrudy** [comment]
Great!

I honestly don’t remember why the delays are there. It might have to do with applescript needing time to access system ui. I adapted this from other workflows, it might be explained elsewhere. And you can certainly experiment with shortening or removing the delays.
