### ISSUE TITLE
Doesn't work in Mojave

### ISSUE THREAD

**Issue by eddzio** [paulrudy/alfred-toggle-do-not-disturb#3]
When triggered, instead of toggling "Do not disturb" it will pull out the notifications menu.

**Comment by paulrudy** [comment]
I noticed this too. Not sure why yet.

**Comment by paulrudy** [comment]
I changed the method for toggling Do Not Disturb. It should work now, although the icon does not reliably change. I'm looking into how to fix that.

**Comment by ohgyun** [comment]
Thanks! Toggling works well.
But the notification dialog not shown before turning on.
Adding `sleep 1` at start of script works for me. :)

**Comment by paulrudy** [comment]
Thanks! Updated with `sleep 7` to allow for full display of the notification.

**Comment by vlom31** [comment]
it would seem it's not detecting the correct DND status.
when it's off, it manages to toggle it to on, but then it can't toggle it back to off as it still detects it as off.

on Mojave 10.14.3
